services:
  # Infrastructure Services
  postgres:
    image: pgvector/pgvector:pg17
    env_file:
      - .env
    ports:
      - "${PORT_POSTGRES_HOST}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../infra/init_db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb:latest
    env_file:
      - .env
    container_name: postgres-webui
    restart: unless-stopped
    ports:
      - "${PORT_POSTGRES_UI}:8081"
    environment:
      PGWEB_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms && rabbitmq-diagnostics -q check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    env_file: .env
    ports:
      - "${PORT_REDIS}:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  
  redis-insight:
    image: redis/redisinsight:latest
    env_file: .env
    ports:
      - "${PORT_REDIS_UI}:5540"
    depends_on:
      - redis
    volumes:
      - redis_insight_data:/data
    restart: unless-stopped


  # Application Services
  main-api:
    build:
      context: ../../
      dockerfile: services/main-api/Dockerfile
    env_file:
      - .env  # Shared environment variables
      
    environment:
      PYTHONPATH: /app/libs:/app/libs/common-py:/app/libs/contracts
    ports:
      - "${PORT_MAIN}:8000"
    volumes:
      - ../../libs:/app/libs
      - ../../infra:/app/infra:ro
      - ../../data:/app/data
      - ../../services/main-api:/app/app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  results-api:
    build:
      context: ../../
      dockerfile: services/results-api/Dockerfile
    env_file:
      - .env
    environment:
      DATA_ROOT: /app/data
      PYTHONPATH: /app/libs:/app/libs/common-py:/app/libs/contracts
    ports:
      - "${PORT_RESULTS}:8080"
    volumes:
      - ../../libs:/app/libs
      - ../../data:/app/data:ro
      - ../../services/results-api:/app/app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    command: ["python", "app/main.py"]

  dropship-product-finder:
    build:
      context: ../../
      dockerfile: services/dropship-product-finder/Dockerfile
    env_file:
      - .env
    environment:
      DATA_ROOT: /app/data
      PYTHONPATH: /app/libs:/app/libs/common-py:/app/libs/contracts
    volumes:
      - ../../libs:/app/libs
      - ../../data:/app/data
      - ../../services/dropship-product-finder:/app/app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: ["python", "app/main.py"]

  video-crawler:
    build:
      context: ../../
      dockerfile: services/video-crawler/Dockerfile
    env_file:
      - .env
      
    environment:
      DATA_ROOT: /app/data
      PYTHONPATH: /app/libs:/app/libs/common-py:/app/libs/contracts
    volumes:
      - ../../libs:/app/libs
      - ../../data:/app/data
      - ../../services/video-crawler:/app/app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    command: ["python", "app/main.py"]

  product-segmentor:
    build:
      context: ../../
      dockerfile: services/product-segmentor/Dockerfile
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/libs:/app/libs/common-py:/app/libs/contracts:/app/libs/vision-common
      DATA_ROOT: /app/data
      TRANSFORMERS_TRUST_REMOTE_CODE: 1
      HF_HUB_ENABLE_HF_TRANSFER: 1 
    volumes:
      - ../../libs:/app/libs
      - ../../data:/app/data
      - ../../services/product-segmentor:/app/app
      - ../../${MODEL_CACHE}:/root/.cache/huggingface
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    command: ["python", "app/main.py"]
    # Uncomment for GPU support
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  vision-embedding:
    build:
      context: ../../
      dockerfile: services/vision-embedding/Dockerfile
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/libs:/app/libs/common-py:/app/libs/contracts:/app/libs/vision-common
    volumes:
      - ../../libs:/app/libs
      - ../../data:/app/data:ro
      - ../../services/vision-embedding:/app/app
      - ../../${MODEL_CACHE}:/root/.cache/huggingface
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      product-segmentor:
        condition: service_started
    restart: unless-stopped
    command: ["python", "app/main.py"]
    # Uncomment for GPU support
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  vision-keypoint:
    build:
      context: ../../
      dockerfile: services/vision-keypoint/Dockerfile
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/libs:/app/libs/common-py:/app/libs/contracts:/app/libs/vision-common
    volumes:
      - ../../libs:/app/libs
      - ../../data:/app/data
      - ../../services/vision-keypoint:/app/app
      - ../../${MODEL_CACHE}:/root/.cache/huggingface
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      product-segmentor:
        condition: service_started
    restart: unless-stopped
    command: ["python", "app/main.py"]

  matcher:
    build:
      context: ../../
      dockerfile: services/matcher/Dockerfile
    env_file:
      - .env
    environment:
      DATA_ROOT: /app/data
      PYTHONPATH: /app/libs:/app/libs/common-py:/app/libs/contracts
    volumes:
      - ../../libs:/app/libs
      - ../../data:/app/data:ro
      - ../../services/matcher:/app/app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    command: ["python", "app/main.py"]

  evidence-builder:
    build:
      context: ../../
      dockerfile: services/evidence-builder/Dockerfile
    env_file:
      - .env
    environment:
      DATA_ROOT: /app/data
      PYTHONPATH: /app/libs:/app/libs/common-py:/app/libs/contracts
    volumes:
      - ../../libs:/app/libs
      - ../../data:/app/data
      - ../../services/evidence-builder:/app/app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    command: ["python", "app/main.py"]

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
  redis_insight_data:

networks:
  default:
    name: product-video-matching