services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"   # HTTP
      - "6334:6334"   # gRPC
    environment:
      QDRANT__TELEMETRY__DISABLE: "true"
    volumes:
      - ./data:/qdrant/storage